function t199_showMenu(recid){var el=$("#rec"+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=$(this),$body=$('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=$(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});$(document).on('click',function(e){var clickedInsideMenu=($(e.target).hasClass('t199__js__menu')||$(e.target).parents('.t199__js__menu').length>0);if(!clickedInsideMenu){$body.removeClass(CLASS_MENU)}})})
$('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=$("#rec"+recid);var $header=el.find('.t199__js__header'),isScrolling=!1,CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if($(window).scrollTop()>0)$header.addClass(CLASS_ACTIVE);else $header.removeClass(CLASS_ACTIVE)}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);$(window).on('scroll',updateHeader)
updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t199__menu a[href='"+url+"']").addClass("t-active");$(".t199__menu a[href='"+url+"/']").addClass("t-active");$(".t199__menu a[href='"+pathname+"']").addClass("t-active");$(".t199__menu a[href='/"+pathname+"']").addClass("t-active");$(".t199__menu a[href='"+pathname+"/']").addClass("t-active");$(".t199__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t199_checkAnchorLinks(recid){if($(window).width()>=960){var t199_navLinks=$("#rec"+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=$(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref($(this));if(typeof t199_cursection.attr("id")!="undefined"){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr("id")]=$(this)});t199_updateSectionsOffsets(t199_sections);$(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));$('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref($(this)).attr("id")].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<(t199_lastCall+t199_interval)){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){$(sections).each(function(){var t199_curSection=$(this);t199_curSection.attr("data-offset-top",t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=$(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr("data-offset-top")>(t199_scrollPosition+300)){t199_navLinks.removeClass('t-active');return null}
$(t199_sections).each(function(e){var t199_curSection=$(this),t199_sectionTop=t199_curSection.attr("data-offset-top"),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(((t199_scrollPosition+300)>=t199_sectionTop)||(t199_sections[0].attr("id")==t199_id&&t199_scrollPosition>=$(document).height()-$(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t453_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t453__item a[href='"+url+"']").addClass("t-active");$(".t453__item a[href='"+url+"/']").addClass("t-active");$(".t453__item a[href='"+pathname+"']").addClass("t-active");$(".t453__item a[href='/"+pathname+"']").addClass("t-active");$(".t453__item a[href='"+pathname+"/']").addClass("t-active");$(".t453__item a[href='/"+pathname+"/']").addClass("t-active")}
function t453_checkAnchorLinks(recid){if($(window).width()>=960){var t453_navLinks=$("#rec"+recid+" .t453__item a:not(.tooltipstered)[href*='#']");if(t453_navLinks.length>0){t453_catchScroll(t453_navLinks)}}}
function t453_catchScroll(t453_navLinks){var t453_clickedSectionId=null,t453_sections=new Array(),t453_sectionIdTonavigationLink={},t453_interval=100,t453_lastCall,t453_timeoutId,t453_offsetTop=$(".t453").attr("data-offset-top");if(typeof t453_offsetTop=="undefined"){t453_offsetTop=0}
t453_navLinks.each(function(){var t453_cursection=t453_getSectionByHref($(this));if(typeof t453_cursection.attr("id")!="undefined"){t453_sections.push(t453_cursection)}
t453_sectionIdTonavigationLink[t453_cursection.attr("id")]=$(this)});t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop);t453_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t453_navLinks.removeClass('t-active');t453_sectionIdTonavigationLink[t453_getSectionByHref($(this)).attr("id")].addClass('t-active');t453_clickedSectionId=t453_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t453_now=new Date().getTime();if(t453_lastCall&&t453_now<(t453_lastCall+t453_interval)){clearTimeout(t453_timeoutId);t453_timeoutId=setTimeout(function(){t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)},t453_interval-(t453_now-t453_lastCall))}else{t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)}})}
function t453_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,offsetTop){var t453_scrollPosition=$(window).scrollTop(),t453_valueToReturn=t453_clickedSectionId;$(t453_sections).each(function(e){var t453_curSection=$(this),t453_sectionTop=t453_curSection.offset().top,t453_id=t453_curSection.attr('id'),t453_navLink=t453_sectionIdTonavigationLink[t453_id];if(t453_scrollPosition>=(t453_sectionTop-offsetTop)||(t453_sections[0].attr("id")==t453_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t453_clickedSectionId==null&&!t453_navLink.hasClass('t-active')){t453_navLinks.removeClass('t-active');t453_navLink.addClass('t-active');t453_valueToReturn=null}else{if(t453_clickedSectionId!=null&&t453_id==t453_clickedSectionId){t453_valueToReturn=null}}
return!1}});return t453_valueToReturn}
function t453_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t453").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");console.log(appearoffset)
if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t453__beforeready')){el.removeClass('t453__beforeready')}}else{el.addClass('t453__beforeready')}}})}
function t604_init(recid){t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);$(window).bind('resize',t_throttle(function(){t604_arrowWidth(recid)},200))}
function t604_show(recid){var el=$("#rec"+recid),play=el.find('.t604__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t604_hide(recid){var el=$("#rec"+recid),body=el.find('.t604__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t604_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t604__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t604_arrowWidth(recid){var el=$("#rec"+recid),arrow=el.find('.t-slds__arrow_wrapper'),slideWidth=el.find('.t-slds__wrapper').width(),windowWidth=$(window).width(),arrowWidth=windowWidth-slideWidth;if(windowWidth>960){arrow.css('width',arrowWidth/2)}else{arrow.css('width','')}}